name: Deploy Backend to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Python and virtual environment
        run: |
          python3 -m venv env
          source env/bin/activate
          pip install --upgrade pip
          pip install zappa
          pip install -r backend/requirements.txt

      - name: Deploy Flask app to Lambda
        working-directory: ./backend
        run: |
          source ../env/bin/activate
          zappa deploy production
